FootballAnalyzes.Web/Models/Games/ByDateListingVM.cs
namespace FootballAnalyzes.Web.Models.Games
{
    using System.Collections.Generic;
    using FootballAnalyzes.Services.Models.Games;

    public class ByDateListingVM
    {
        public IEnumerable<ByDateSM> GamesByDate { get; set; }
        public Pagination Page { get; set; }
    }
}

FootballAnalyzes.Web/Models/Games/GameDetailsVM.cs
namespace FootballAnalyzes.Web.Models.Games
{
    using System.Collections.Generic;
    using FootballAnalyzes.Services.Admin.Models;

    public class GameDetailsVM
    {
        public FootballGamePM CurrentGame { get; set; }
        public IEnumerable<FootballGamePM> HomeTeamGames { get; set; }
        public IEnumerable<FootballGamePM> AwayTeamGames { get; set; }
        public IEnumerable<FootballGamePM> GamesBeteenBothTeams { get; set; }

    }
}

FootballAnalyzes.Web/Models/Games/GameListingVM.cs
namespace FootballAnalyzes.Web.Models.Games
{
    using System.Collections.Generic;
    using FootballAnalyzes.Services.Models.Games;

    public class GameListingVM
    {
        public IEnumerable<FootballGameSM> Games { get; set; }
        public Pagination Page { get; set; }
    }
}

FootballAnalyzes.Web/Models/Games/GameListingWithoutResultVM.cs
namespace FootballAnalyzes.Web.Models.Games
{
    using System.Collections.Generic;
    using FootballAnalyzes.Services.Models.Games;

    public class GameListingWithoutResultVM
    {
        public IEnumerable<FootballGameSM> Games { get; set; }
        public Pagination Page { get; set; }
    }
}

FootballAnalyzes.Web/Models/Pagination.cs
namespace FootballAnalyzes.Web.Models
{
    using System;

    using static FootballAnalyzes.Services.ServiceConstants;

    public class Pagination
    {
        public int TotalCount { get; set; }
        public int TotalPages => (int)Math.Ceiling((double)this.TotalCount / GamesPageSize);
        public int CurrentPage { get; set; }
        public int PreviousPage => this.CurrentPage == 1 ? 1 : this.CurrentPage - 1;
        public int NextPage => this.CurrentPage == this.TotalPages ? this.TotalPages : this.CurrentPage + 1;
    }
}

FootballAnalyzes.Web/Areas/Admin/Controllers/UsersController.cs
namespace FootballAnalyzes.Web.Areas.Admin.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using FootballAnalyzes.Data.Models;
    using FootballAnalyzes.Services.Admin;
    using FootballAnalyzes.Web.Areas.Admin.Models.Users;
    using FootballAnalyzes.Web.Infrastructure.Extensions;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    public class UsersController : BaseAdminController
    {
        private readonly IAdminUserService users;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public UsersController(IAdminUserService users, RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            this.users = users;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = this.users.All();

            foreach (var user in users)
            {
                var currentUser = await this.userManager.FindByIdAsync(user.Id);
                var userRoles = await this.userManager.GetRolesAsync(currentUser);
                user.CurrentRole = string.Join(", ", userRoles);
            }

            var roles = this.roleManager
                .Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
                .ToList();

            return View(new AdminUsersVM
            {
                Users = users,
                Roles = roles
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddToRole(AddUserToFM model)
        {
            var roleExist = await this.roleManager.RoleExistsAsync(model.Role);
            var user = await this.userManager.FindByIdAsync(model.UserId);

            if (!roleExist || user == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid identity details.");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            TempData.AddSuccessMessage($"User {user.UserName} success added to {model.Role} role.");
            await this.userManager.AddToRoleAsync(user, model.Role);

            return RedirectToAction(nameof(Index));
        }
    }
}

FootballAnalyzes.Web/Controllers/GamesController.cs
namespace FootballAnalyzes.Web.Controllers
{
    using System;
    using System.Globalization;
    using FootballAnalyzes.Services;
    using FootballAnalyzes.Services.Models.Games;
    using FootballAnalyzes.Web.Models;
    using FootballAnalyzes.Web.Models.Games;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    
    [Authorize(Roles = WebConstants.AdministratorAndCustomerRoles)]
    public class GamesController : Controller
    {
        private readonly IGameService games;
        
        public GamesController(IGameService games)
        {
            this.games = games;
        }

        public IActionResult All(int page = 1)
        {
            page = page < 1 ? 1 : page;

            var allGames = new GameListingVM
            {   
                Games = this.games.All(page),
                Page = new Pagination
                {
                    TotalCount = this.games.TotalGamesCount(),
                    CurrentPage = page
                }                
            };

            return View(allGames);
        }

        public IActionResult Next(int page = 1)
        {
            page = page < 1 ? 1 : page;

            var nextGames = new GameListingVM
            {
                Games = this.games.Next(page),
                Page = new Pagination
                {
                    TotalCount = this.games.TotalNextGamesCount(),
                    CurrentPage = page
                }
            };

            return View(nextGames);
        }

        public IActionResult ByDate(int page = 1)
        {
            page = page < 1 ? 1 : page;

            var model = new ByDateListingVM
            {
                GamesByDate = this.games.GroupByDate(page),
                Page = new Pagination
                {
                    TotalCount = games.TotalByDateCount(),
                    CurrentPage = page
                }
            };

            return View(model);
        }

        public IActionResult DateGames(string date, int page = 1)
        {
            page = page < 1 ? 1 : page;
            DateTime currentDate = DateTime.ParseExact(date, "dd-MM-yyyy", CultureInfo.InvariantCulture);

            var games = this.games.DateGames(currentDate, page);

            return View(games);
        }

        public IActionResult WithoutResult(string date, int page = 1)
        {
            page = page < 1 ? 1 : page;

            DateTime currentDate = DateTime.ParseExact(date, "dd-MM-yyyy", CultureInfo.InvariantCulture);

            var nextGames = new GameListingWithoutResultVM
            {
                Games = this.games.WithoutResult(currentDate, page),
                Page = new Pagination
                {
                    TotalCount = this.games.TotalCurrnetDateGamesCount(currentDate),
                    CurrentPage = page
                }
            };

            return View(nextGames);
        }

        [Authorize(Roles = WebConstants.AdministratorRole)]
        public IActionResult EditGame(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var editGame = this.games.FindGameForEdit(id);

            return View(editGame);
        }

        [HttpPost]
        [Authorize(Roles = WebConstants.AdministratorRole)]
        public IActionResult EditGame(EditGameSM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var updateGameToDB = this.games.EditGame(model.Id, model.FullTimeResult.HomeTeamGoals, model.FullTimeResult.AwayTeamGoals);

            if (!updateGameToDB)
            {
                return NotFound();
            }

            string dateString = model.MatchDate.ToString("dd-MM-yyyy");

            return RedirectToAction(nameof(WithoutResult), new { date = dateString });
        }

        public IActionResult GameDetails(int gameId, int page = 1)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var currentGame = this.games.ById(gameId);

            if (currentGame == null)
            {
                return NotFound();
            }

            var hTGames = this.games.TeamGames(currentGame.MatchDate, currentGame.HomeTeam.Id, page);
            var aTGames = this.games.TeamGames(currentGame.MatchDate, currentGame.AwayTeam.Id, page);
            var gamesBetweenBothTeams = this.games.BetweenBothTeams(currentGame.MatchDate, currentGame.HomeTeam.Id, currentGame.AwayTeam.Id);

            var model = new GameDetailsVM
            {
                CurrentGame = currentGame,
                HomeTeamGames = hTGames,
                AwayTeamGames = aTGames,
                GamesBeteenBothTeams = gamesBetweenBothTeams
            };

            return View(model);
        }
    }
}

FootballAnalyzes.Web/Controllers/LeaguesController.cs
namespace FootballAnalyzes.Web.Controllers
{
    using FootballAnalyzes.Services;
    using FootballAnalyzes.Web.Models;
    using FootballAnalyzes.Web.Models.Leagues;
    using Microsoft.AspNetCore.Mvc;


    public class LeaguesController : Controller
    {
        private readonly ILeagueService leagues;

        public LeaguesController(ILeagueService leagues)
        {
            this.leagues = leagues;
        }

        public IActionResult All(int page = 1)
        {
            var allLeagues = new LeagueListingVM
            {
                Leagues = this.leagues.All(page),
                Page = new Pagination
                {
                    TotalCount = this.leagues.TotalLeaguesCount(),
                    CurrentPage = page
                }
            };

            return View(allLeagues);
        }

        public IActionResult ById(int leagueId)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var name = this.leagues.NameById(leagueId);
            var games = this.leagues.LeagueGames(leagueId);

            if (name == null)
            {
                return NotFound();
            }

            return View(new LeagueDetailsVM
            {
                Name = name,
                Games = games
            }); ;
        }
    }
}

FootballAnalyzes.Web/Controllers/PredictionsController.cs
namespace FootballAnalyzes.Web.Controllers
{
    using FootballAnalyzes.Services;
    using Microsoft.AspNetCore.Mvc;

    public class PredictionsController : Controller
    {
        private readonly IPredictionService predictions;

        public PredictionsController(IPredictionService predictions)
        {
            this.predictions = predictions;
        }

        public IActionResult All()
        {
            var model = this.predictions.All();

            return View(model);
        }

        public IActionResult Predict(string name)
        {
            var model = this.predictions.PredictGames(name);

            return View(model);
        }
    }
}

FootballAnalyzes.Web/Controllers/TeamsController.cs
namespace FootballAnalyzes.Web.Controllers
{
    using FootballAnalyzes.Services;
    using FootballAnalyzes.Web.Models;
    using FootballAnalyzes.Web.Models.Teams;
    using Microsoft.AspNetCore.Mvc;

    public class TeamsController : Controller
    {
        private readonly ITeamService teams;

        public TeamsController(ITeamService teams)
        {
            this.teams = teams;
        }

        public IActionResult All(int page = 1)
        {
            var allTeams = new TeamListingVM
            {
                Teams = this.teams.All(page),
                Page = new Pagination
                {
                    CurrentPage = page,
                    TotalCount = this.teams.TotalTeamsCount()
                }
            };

            return View(allTeams);
        }

        public IActionResult ById(int teamId)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var name = this.teams.NameById(teamId);
            var games = this.teams.TeamGames(teamId);

            if (name == null)
            {
                return NotFound();
            }

            return View(new TeamDetailsVM
            {
                Name = name,
                Games = games
            });
        }
    }
}

FootballAnalyzes.Web/Views/Shared/_GamesTable.cshtml
@model IEnumerable<FootballGamePM>

<table class="table table-bordered table-hover table-nowrap">
    <thead>        
        <tr>
            <th></th>
            <th>Date</th>
            <th>League </th>
            <th>Home Team</th>
            <th>Away Team</th>
            @if (Model.Any(g => g.FullTimeResult != null))
            {
                <th>FT</th>
                <th>HT</th>
                <th>Statistic</th>
            }
            <th>HTWin</th>
            <th>Draw</th>
            <th>ATWin</th>
            <th>HTWBBT</th>
            <th>ATWBBT</th>
            <th>Over8Cor</th>
            <th>Under8Cor</th>
            <th>HTCor</th>
            <th>ATCor</th>
            <th>SumCor</th>
        </tr>
    </thead>
    <tbody>
        @{ int count = 0; }
        @foreach (var game in Model)
        {
            <tr class="@(count % 2 == 1 ? "oddRow" : "")">
                <td><a asp-controller="Games" asp-action="GameDetails" asp-route-gameId="@game.Id">Info</a></td>
                <td><a asp-controller="Games" asp-action="DateGames" asp-route-date="@(game.MatchDate.ToString("dd-MM-yyyy"))">@(game.MatchDate.ToString("dd-MM-yy HH:mm"))</a></td>
                <td><a asp-controller="Leagues" asp-action="ById" asp-route-leagueId="@game.League.Id">@($"{game.League.Country},{game.League.Name},{game.League.Year},{game.League.Stage}")</a></td>

                @if (game.FullTimeResult != null)
                {
                    <td class="@(game.FullTimeResult.Result == ResultEnum.H ? "winnerBold" : "")"><a asp-controller="Teams" asp-action="ById" asp-route-teamId="@game.HomeTeam.Id">@game.HomeTeam.Name</a></td>
                    <td class="@(game.FullTimeResult.Result == ResultEnum.A ? "winnerBold" : "")"><a asp-controller="Teams" asp-action="ById" asp-route-teamId="@game.AwayTeam.Id">@game.AwayTeam.Name</a></td>
                }
                else
                {
                    <td><a asp-controller="Teams" asp-action="ById" asp-route-teamId="@game.HomeTeam.Id">@game.HomeTeam.Name</a></td>
                    <td><a asp-controller="Teams" asp-action="ById" asp-route-teamId="@game.AwayTeam.Id">@game.AwayTeam.Name</a></td>
                }

                @if (Model.Any(g => g.FullTimeResult != null))
                {
                    @if (game.FullTimeResult != null)
                    {
                        <td>@($"{ game.FullTimeResult.HomeTeamGoals} - {game.FullTimeResult.AwayTeamGoals}")</td>
                    }
                    else
                    {
                        <td></td>
                    }
                    @if (game.FirstHalfResult != null)
                    {
                        <td>@($"{game.FirstHalfResult.HomeTeamGoals} - {game.FirstHalfResult.AwayTeamGoals}")</td>
                    }
                    else
                    {
                        <td></td>
                    }
                    @if (game.GameStatistic != null)
                    {
                        <td>@($"{game.GameStatistic.ToString()}")</td>
                    }
                    else
                    {
                        <td></td>
                    }
                }

                @if (game.Predictions.Count() != 0)
                {
                    <td>@game.Predictions.Where(p => p.Name == ServiceConstants.HTWin).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>
                    <td>@game.Predictions.Where(p => p.Name == ServiceConstants.Draw).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>
                    <td>@game.Predictions.Where(p => p.Name == ServiceConstants.ATWin).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>

                    @if (game.Predictions.Any(p => p.Name == ServiceConstants.HTWinBetweenBothTeams))
                    {
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.HTWinBetweenBothTeams).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.ATWinBetweenBothTeams).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>
                    }
                    else
                    {
                        <td></td>
                        <td></td>
                    }
                    @if (game.Predictions.Any(p => p.Name == ServiceConstants.HTCorners))
                    {
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.Over8Corners).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.Under12Corners).Select(p => p.Procent.ToString("0.00")).FirstOrDefault()</td>
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.HTCorners).Select(p => p.Procent.ToString("0")).FirstOrDefault()</td>
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.ATCorners).Select(p => p.Procent.ToString("0")).FirstOrDefault()</td>
                        <td>@game.Predictions.Where(p => p.Name == ServiceConstants.SumCorners).Select(p => p.Procent.ToString("0")).FirstOrDefault()</td>
                    }
                    else
                    {
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    }
                }
                else
                {
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                }
            </tr>
            count++;
        }
    </tbody>
</table>

FootballAnalyzes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Football Analyzes</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" type="text/css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Football Analyzes</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.IsInRole(WebConstants.AdministratorRole) || User.IsInRole(WebConstants.CustomerRole))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">
                                Games
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Games" asp-action="All">All</a></li>
                                <li><a asp-area="" asp-controller="Games" asp-action="Next">Next</a></li>
                                <li><a asp-area="" asp-controller="Games" asp-action="ByDate">By Date</a></li>
                            </ul>
                        </li>
                        <li><a asp-area="" asp-controller="Teams" asp-action="All">Teams</a></li>
                        <li><a asp-area="" asp-controller="Leagues" asp-action="All">Leagues</a></li>
                        <li><a asp-area="" asp-controller="Predictions" asp-action="All">Predictions</a></li>
                    }
                    
                    @if (User.IsInRole(WebConstants.AdministratorRole))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">
                                Update DB
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="Admin" asp-controller="Update" asp-action="Index">Add new games</a></li>
                                <li><a asp-area="Admin" asp-controller="Update" asp-action="UpdateOldGames">Update old games</a></li>
                                <li><a asp-area="Admin" asp-controller="Update" asp-action="Predict">Predict old games</a></li>
                            </ul>
                        </li>
                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessage))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempDataSuccessMessage]
            </div>
        }
        @if (TempData.ContainsKey(WebConstants.TempDataErrorMessage))
        {
            <div class="alert alert-danger">
                @TempData[WebConstants.TempDataErrorMessage]
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Football Analyzes</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FootballAnalyzes.Web/Views/Shared/_Pagination.cshtml
@model Pagination

<ul class="pagination">
    <li class="page-item">
        @{ 
            string disablePrevious = Model.CurrentPage == 1 ? "disable" : "";
        }
        <a class="page-link @disablePrevious" href="?page=@Model.PreviousPage" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>
    @{ 
        int startPage = Model.CurrentPage - WebConstants.PagesNumberCount <= 0 ? 1 : Model.CurrentPage - WebConstants.PagesNumberCount;
        int endPage = Model.CurrentPage + WebConstants.PagesNumberCount >= Model.TotalPages ? Model.TotalPages : Model.CurrentPage + WebConstants.PagesNumberCount;
    }
    @for (int i = startPage; i <= endPage; i++)
    {
        if (i == Model.CurrentPage)
        {
            <li class="page-item"><a class="page-link current-page-item" href="?page=@i"><strong>@i</strong></a></li>
        }
        else
        {
            <li class="page-item"><a class="page-link" href="?page=@i">@i</a></li>
        }
    }
    <li class="page-item">
        @{
            string disableNext = Model.CurrentPage == Model.TotalPages ? "disable" : "";
        }
        <a class="page-link @disableNext" href="?page=@Model.NextPage" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
</ul>