FootballAnalyzes.Web/Areas/Admin/Models/Update/DeleteGamesByDateVM.cs
namespace FootballAnalyzes.Web.Areas.Admin.Models.Update
{
    public class DeleteGamesByDateVM
    {
        public string Date { get; set; }
        public int DeleteGamesCount { get; set; }
    }
}

FootballAnalyzes.Web/Areas/Admin/Models/Update/UpdateDetailsFM.cs
namespace FootballAnalyzes.Web.Areas.Admin.Models.Update
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class UpdateDetailsFM : IValidatableObject
    {
        public string DatesInfo { get; set; }

        [Display(Name = "Next Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime NextGamesDate { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.NextGamesDate <= DateTime.UtcNow.AddDays(-1))
            {
                yield return new ValidationResult("Start date should be today or in the future.");
            }
        }
    }
}

FootballAnalyzes.Web/Areas/Admin/Models/Update/UpdateOldGamesForResultFM.cs
namespace FootballAnalyzes.Web.Areas.Admin.Models.Update
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class UpdateOldGamesForResultFM : IValidatableObject
    {
        [Required]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.StartDate > this.EndDate)
            {
                yield return new ValidationResult("Start date should be before end date.");
            }
        }
    }
}

FootballAnalyzes.Web/Areas/Admin/Controllers/UpdateController.cs
namespace FootballAnalyzes.Web.Areas.Admin.Controllers
{
    using System;
    using System.Globalization;
    using FootballAnalyzes.Services.Admin;
    using FootballAnalyzes.Web.Areas.Admin.Models.Update;
    using FootballAnalyzes.Web.Controllers;
    using FootballAnalyzes.Web.Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class UpdateController : BaseAdminController
    {
        private readonly IAdminUpdateService updates;

        public UpdateController(IAdminUpdateService updates)
        {
            this.updates = updates;
        }

        public IActionResult Index()
        {
            string updateInfo = this.updates.UpdateDatesInfo();

            return View(new UpdateDetailsFM
            {
                DatesInfo = updateInfo,
                NextGamesDate = DateTime.Now
            });
        }

        [HttpPost]
        public IActionResult Index(UpdateDetailsFM model)
        {
            if (!ModelState.IsValid)
            {
                return this.BadRequest();
            }

            string message = this.updates.UpdateDb(model.NextGamesDate);

            TempData.AddSuccessMessage($"{message}");

            return this.RedirectToAction(nameof(Index));
        }
                
        public IActionResult DeleteByDate(string date)
        {
            int deleteGamesCount = this.updates.DeleteGamesByDateCount(date);

            return View(new DeleteGamesByDateVM
            {
                Date = date,
                DeleteGamesCount = deleteGamesCount
            });
        }
                
        public IActionResult ConfirmDeleteByDate(string date, int count)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(GamesController.ByDate), "Games", new { area = "" });
            }

            this.updates.DeleteGamesByDate(date);
            TempData.AddSuccessMessage($"Successfull deleted {count} games.");

            return RedirectToAction(nameof(GamesController.ByDate), "Games", new { area = "" });
        }
        
        public IActionResult UpdateOldGames()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UpdateOldGames(UpdateOldGamesForResultFM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var message = this.updates.UpdateOldGames(model.StartDate, model.EndDate);

            TempData.AddSuccessMessage($"{message}");

            return RedirectToAction(nameof(GamesController.ByDate), "Games", new { area = "" });
        }

        public IActionResult UpdateCurrentDateGames(string date)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            DateTime currentDate = DateTime.ParseExact(date, "dd-MM-yyyy", CultureInfo.InvariantCulture);

            var message = this.updates.UpdateOldGames(currentDate, currentDate);

            TempData.AddSuccessMessage($"{message}");

            return RedirectToAction(nameof(GamesController.ByDate), "Games", new { area = "" });
        }

        public IActionResult Predict()
        {
            string message = this.updates.MakePredictionToOldGames();

            TempData.AddSuccessMessage($"{message}");

            return RedirectToAction(nameof(Index));
        }

        public IActionResult PredictNextGames(string date)
        {
            DateTime currentDate = DateTime.ParseExact(date, "dd-MM-yyyy", CultureInfo.InvariantCulture);

            string message = this.updates.MakePredictionToNewGames(currentDate);

            TempData.AddSuccessMessage($"{message}");

            return RedirectToAction(nameof(Index));
        }
    }
}

FootballAnalyzes.Web/Areas/Admin/Views/Update/DeleteByDate.cshtml
@model DeleteGamesByDateVM
@{
    ViewData["Title"] = "DeleteByDate";
}

<h3>Are you sure to delete all @Model.DeleteGamesCount games from @Model.Date date?</h3>
<a asp-area="Admin" asp-controller="Update" asp-action="ConfirmDeleteByDate" asp-route-date="@Model.Date" asp-route-count="@Model.DeleteGamesCount" class="btn btn-primary btn-sm btn-danger">Delete Games</a>

FootballAnalyzes.Web/Areas/Admin/Views/Update/Index.cshtml
@model UpdateDetailsFM
@{
    ViewData["Title"] = "Update DB";
}

<h2>@ViewData["Title"]</h2>
 
<div class="row table-bordered">
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
            <h4>Make analyzes for next games</h4>
            <hr />
            <p>@Model.DatesInfo</p>
            <div asp-validation-summary="All" class="text-danger"></div>          
            <div class="form-group">
                <label asp-for="NextGamesDate"></label>
                <input asp-for="NextGamesDate" class="form-control" max="@DateTime.Now.Date"/>
                <span asp-validation-for="NextGamesDate" class="text-danger"></span>
                <small>Date: @DateTime.Now.ToShortDateString() @DateTime.Now.ToShortTimeString()</small>
            </div>          
            <button type="submit" class="btn btn-default btn-primary">Update DB</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

FootballAnalyzes.Web/Areas/Admin/Views/Update/UpdateOldGames.cshtml
@model UpdateOldGamesForResultFM
@{
    ViewData["Title"] = "Update DB";
}
<h2>@ViewData["Title"]</h2>

<div class="row table-bordered">
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
            <h4>Make analyzes for next games</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartDate"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default btn-primary">Update DB</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}